/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2018-03-15 17:42:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.PrintWriter;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.PrintWriter");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scale=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href =\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href =\"css/custom.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href =\"css/default.css\">\r\n");
      out.write("<title>SCREEN DOOR</title>\r\n");
      out.write("</head>\r\n");
      out.write("<script>\r\n");
      out.write("$('#myCarousel').carousel();\r\n");
      out.write("var winWidth = $(window).innerWidth();\r\n");
      out.write("$(window).resize(function () {\r\n");
      out.write("\r\n");
      out.write("    if ($(window).innerWidth() < winWidth) {\r\n");
      out.write("        $('.carousel-inner>.item>img').css({\r\n");
      out.write("            'min-width': winWidth, 'width': winWidth\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("    else {\r\n");
      out.write("        winWidth = $(window).innerWidth();\r\n");
      out.write("        $('.carousel-inner>.item>img').css({\r\n");
      out.write("            'min-width': '', 'width': ''\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t");

		String userID = null;
		if(session.getAttribute("userID")!=null){
			userID = (String)session.getAttribute("userID");
		}
		
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-fixed-top\" style=\"background:black;overflow:visible;\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<span class =\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class =\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class =\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" style=\"font-family:TESLA;color:#F8F8FF;\" href=\"main.jsp\">SCREENDOOR</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"main.jsp\" accesskey=\"1\" style=\"font-family:Gotham Light;color:#F8F8FF;\">MAIN</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.jsp\" style=\"font-family:Gotham Light;color:#F8F8FF;\">ABOUT</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"bbs.jsp\" style=\"font-family:Gotham Light;color:#F8F8FF;\">NOTIFY</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");

				if(userID ==null){
				
			
      out.write("\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class = \"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\" style=\"font-family:Gotham Light;color:#F8F8FF;\">SIGN IN<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"login.jsp\" style=\"font-family:Gotham Light\">LOGIN</a></li>\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"join.jsp\" style=\"font-family:Gotham Light\">JOIN</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				}else if(userID.equals("admin")){
			
      out.write("\r\n");
      out.write("\t\t\t<nav class=\"navbar navbar-fixed-top\" style=\"background:black;overflow:visible;\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("\t\t\t\t\tdata-toggle=\"collapse\" data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("\t\t\t\t\taria-expanded=\"false\">\r\n");
      out.write("\t\t\t\t\t<span class =\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class =\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t\t<span class =\"icon-bar\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" style=\"font-family:TESLA;color:#F8F8FF;\" href=\"main.jsp\">S-LAB</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"main.jsp\" accesskey=\"1\" style=\"font-family:Gotham Light;color:#F8F8FF;\">MAIN</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"about.jsp\" style=\"font-family:Gotham Light;color:#F8F8FF;\">ABOUT</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"bbs.jsp\" style=\"font-family:Gotham Light;color:#F8F8FF;\">BOARD</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"form.jsp\" style=\"font-family:Gotham Light;color:#F8F8FF;\">업로드</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class = \"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\" style=\"font-family:Gotham Light;color:#F8F8FF;\">MANAGE<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"logoutAction.jsp\" style=\"font-family:Gotham Light\">LOGOUT</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				}else{
			
      out.write("\r\n");
      out.write("\t\t\t<ul class = \"nav navbar-nav navbar-right\">\r\n");
      out.write("\t\t\t\t<li class=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"dropdown-toggle\"\r\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\"\r\n");
      out.write("\t\t\t\t\t\taria-expanded=\"false\" style=\"font-family:Gotham Light;color:#F8F8FF;\">MANAGE<span class=\"caret\"></span></a>\r\n");
      out.write("\t\t\t\t\t<ul class=\"dropdown-menu\">\r\n");
      out.write("\t\t\t\t\t\t<li ><a href=\"logoutAction.jsp\" style=\"font-family:Gotham Light\">LOGOUT</a></li>\r\n");
      out.write("\t\t\t\t\t</ul>\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("<!-- <div align=\"center\" class=\"container\" style=\"padding-right: 0px;padding-left: 0px;margin-right: 0px;margin-left: 0px;\">-->\r\n");
      out.write("\t\t<div  id=\"myCarousel\" class=\"carousel slide\" style=\"width: 100%;max-width: 100%;\">\r\n");
      out.write("\t\t\t  <ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t    <li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t    <li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t    <li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t  </ol>\r\n");
      out.write("\t\t\t  <div class=\"carousel-inner\" style=\"\"role=\"listbox\">\r\n");
      out.write("\t\t\t    <div class=\"item active\">\r\n");
      out.write("\t\t\t      <img class=\"d-block img-fluid\" src=\"image/banner-first.jpg\" alt=\"First slide\">\r\n");
      out.write("\t\t\t    \t<div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("    \t\t\t\t\t<h1 style=\"font-family:Gotham Light;color:#F8F8FF;\">Development</h1>\r\n");
      out.write("    \t\t\t\t\t<p style=\"font-family:Gotham Light;color:#F8F8FF;\">All new technology</p>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"item\">\r\n");
      out.write("\t\t\t      <img class=\"d-block img-fluid\" src=\"image/banner-second.jpg\" alt=\"Second slide\">\r\n");
      out.write("\t\t\t      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("    \t\t\t\t\t<h1 style=\"font-family:Gotham Light;color:#F8F8FF;\">Hacking</h1>\r\n");
      out.write("    \t\t\t\t\t<p style=\"font-family:Gotham Light;color:#F8F8FF;\">Web, Android, System</p>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t    <div class=\"item\">\r\n");
      out.write("\t\t\t      <img class=\"d-block img-fluid\" src=\"image/banner-third.jpg\" alt=\"Third slide\">\r\n");
      out.write("\t\t\t      <div class=\"carousel-caption d-none d-md-block\">\r\n");
      out.write("    \t\t\t\t\t<h1 style=\"font-family:Gotham Light;color:#F8F8FF;\" >SCREEN DOOR</h1>\r\n");
      out.write("    \t\t\t\t\t<p style=\"font-family:Gotham Light;color:#F8F8FF;\">KNUT</p>\r\n");
      out.write("    \t\t\t\t</div>\r\n");
      out.write("\t\t\t    </div>\r\n");
      out.write("\t\t\t  </div>\r\n");
      out.write("\t\t\t    <a class=\"left carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"prev\">\r\n");
      out.write("\t\t\t    \t<span class=\"glyphicon glyphicon-chevron-left\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t  \t</a>\r\n");
      out.write("\t\t\t  \t<a class=\"right carousel-control\" href=\"#myCarousel\" role=\"button\" data-slide=\"next\">\r\n");
      out.write("\t\t\t   \t\t<span class=\"glyphicon glyphicon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("\t\t\t  \t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t<!-- </div>-->\r\n");
      out.write("\t<!-- container  -->\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"wrapper\">\r\n");
      out.write("\t<div id=\"three-column\" class=\"container\" align=\"center\">\r\n");
      out.write("\t\t<div class=\"title\">\r\n");
      out.write("\t\t\t<h2>공지사항</h2>\r\n");
      out.write("\t\t\t<span class=\"byline\">변경예정</span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxA\">\r\n");
      out.write("\t\t\t<span class=\"fa fa-cloud-download\"></span>\r\n");
      out.write("\t\t\t<h1>Model A</h1>\r\n");
      out.write("\t\t\t<a href=\"reserve.jsp\" class=\"button button-alt\">Reserve</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxB\">\r\n");
      out.write("\t\t\t<span class=\"fa fa-cogs\"></span>\r\n");
      out.write("\t\t\t<h1>Model S</h1>\r\n");
      out.write("\t\t\t<a href=\"reserve.jsp\" class=\"button button-alt\">Reserve</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"boxC\">\r\n");
      out.write("\t\t\t<span class=\"fa fa-wrench\"></span>\r\n");
      out.write("\t\t\t<h1>Model X</h1>\r\n");
      out.write("\t\t\t<a href=\"reserve.jsp\" class=\"button button-alt\">Reserve</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<nav class=\"navbar\" style=\"background:white;overflow:visible;\">\r\n");
      out.write("    \t\t<p class=\"jumbo\" style=\"color:black;\">© 2017 SCREENDOOR. All Rights Reserved</p>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("\t<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
